apiVersion: v1
kind: ConfigMap
metadata:
  name: "temporal-dynamic-config"
  namespace: temporal-test-tarun
  labels:
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-0.18.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/version: 1.18.0
    app.kubernetes.io/part-of: temporal
data:
  dynamic_config.yaml: |-